
# Site settings

url: "http://www.nicolaspettican.com"

# baseurl: #/home

# Google tracking id

google-tracking-id: "UA-77716753-1"

force-https: False

#############
# HTML Head #
#############

lang: "en"
author: "Nicolas Pettican"
title: "Nicolas Pettican"
description: "Nicolas Pettican's official personal website."
keywords: "nicolas pettican, nick pettican, pettican, healthcare, programming, marketing, pharma, CV, jekyll"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/bioinformatics.ico"

background-img: "../img/back_focus.jpg"
blog-landing-img: "../img/desktop.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Data analyst"
  - text: "Python programmer"
  - text: "Market researcher"
  - text: "Healthcare communicator"

me-img: "/img/guy_white.gif"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: False

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: False
google-plus-share: True
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "pettiblog"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/lynx.png"
    date: "September 2016 - Present"
    description: "**Research Executive** for Strategy and Planning at **Havas Lynx**"
  - image: "/img/timeline/bioinformatics.png"
    date: "September 2015 - Present"
    description: "Graduated with a **Master's in Bioinformatics and Systems Biology** from the University of Manchester"
  - image: "/img/timeline/world_small.gif"
    date: "February 2016 - Today"
    description: "Creating illustrations and animations for **science communication** as a hobby"
  - image: "/img/timeline/askme.png"
    date: "January 2016 - August 2016"
    description: "University of Manchester Postgraduate Student Ambassador"
  - image: "/img/timeline/presentation.gif"
    date: "October 2015 - August 2016"
    description: "**President** of the University of Manchester [Bioinformatics Society](http://uombio.info)"
  - image: "/img/timeline/code_white.gif"
    date: "October 2015 - Present"
    description: "Learned to **code** in Python, R, Java and Perl. Learned **web design** with HTML, CSS and JavaScript"
  - image: "/img/timeline/grad.jpg"
    date: "July 2015"
    description: "Graduated with a **BSc with Honours in Biotechnology with Enterprise** from the University of Manchester"
  - image: "/img/timeline/graph_small.gif"
    date: "September 2013 - June 2015"
    description: "Learned **Market Research** and **Data Analysis** for assignments in the Manchester Business School"
  - image: "/img/timeline/cell_small.gif"
    date: "June 2012 - June 2015"
    description: "Undertook modules in Pharmacology, Microbiology, Biotechnology, Neuroscience, Enterprise and Management"
  - image: "/img/timeline/folss.jpg"
    date: "October 2012 - March 2015"
    description: "**Marketing & Events Manager** and **Vice President** of the Faculty of Life Sciences Society"
  - image: "/img/timeline/social_media.jpg"
    date: "October 2012 - November 2014"
    description: "**P.R.**, **Marketing Rep** and **Event Manager**"
  - image: "/img/timeline/bspp.jpg"
    date: "July 2014 - September 2014"
    description: "**Research Assistant** at the University of Sheffield"

# First image of the Timeline

timeline-img: "/img/guy_white.gif"

###########
# Contact #
###########

email: "nicolaspettican@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Evil Scientist | Healthcare Communicator | Programmer | Coffee Drinker | Analyst | Spanglish"
author_blurb_image: "/img/world_small.gif"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/nicolas.pettican"
  - title: "instagram"
    url: "https://instagram.com/nickpettican"
  - title: "linkedin"
    url: "https://linkedin.com/in/nickpettican"
  - title: "twitter"
    url: "https://twitter.com/pettitweets"
  - title: "github"
    url: "https://github.com/nickpettican"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

four-o-four-img: "/img/code_white.gif"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  Aboutme: 'aboutme'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
